-- Create Admin User Script
-- Run this after schema_v2.sql migration
-- Password: admin123 (BCrypt hash will be generated by Java utility)

-- First, ensure the user_role enum exists
DO $$ BEGIN
    CREATE TYPE user_role AS ENUM ('ADMIN', 'USER');
EXCEPTION
    WHEN duplicate_object THEN null;
END $$;

-- Insert admin user (you'll need to replace the password_hash with a BCrypt hash)
-- Use the GenerateAdminHash.java utility to generate the hash first
INSERT INTO users (username, email, password_hash, full_name, role, is_deleted, created_at, updated_at)
VALUES (
    'admin',
    'admin@kanban.com',
    '$2a$10$N9qo8uLOickgx2ZMRZoMyeIjZAgcfl7p92ldGxad68LJZdL17lhWy', -- This is BCrypt hash for 'admin123'
    'System Administrator',
    'ADMIN',
    FALSE,
    NOW(),
    NOW()
)
ON CONFLICT (username) DO UPDATE SET
    role = 'ADMIN',
    email = EXCLUDED.email,
    full_name = EXCLUDED.full_name,
    updated_at = NOW();

